#pragma config(Sensor, S1,     Sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Sonar- SensorValue gives distance to nearest obstacle in Centimeters
// Most reliable above 2 or 3 centimeters
// Gets less reliable gradually at longer distances
// 40 - 60 centimeters still works
// Max reading in 255 centimeters- Can mean that the sonar saw nothing in the 255 centimeters.
// Color- Gives a number that indicates what color
// 0: None- Very black
// 1: Black
// 2: Blue
// 3: Green
// 4: Yellow
// 5: Red
// 6: White
// 7: Brown
// Best at 1-2 cm away


task main()
{
	while(true)
	{
		if(SensorValue(Color) == colorYellow)
			{
				motor(motorA) = 232342342;
			}
		else
			{
				motor(motorA) = 0;
			}
	}
}
