#pragma config(Sensor, S1,     Color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     Sonar,          sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Sonar- SensorValue gives distance to nearest obstacle in Centimeters
// Most reliable above 2 or 3 centimeters
// Gets less reliable gradually at longer distances
// 40 - 60 centimeters still works
// Max reading in 255 centimeters- Can mean that the sonar saw nothing in the 255 centimeters.
// Color- Gives a number that indicates what color
// 0: None- Very black
// 1: Black
// 2: Blue
// 3: Green
// 4: Yellow
// 5: Red
// 6: White
// 7: Brown
// Best at 1-2 cm away
// Right motor is slot D
// Left motor is slot A


task main()
{


	while(SensorValue(Sonar) >= 10)
	{
		motor(motorA) = 50;
		motor(motorD) = 50;
	}
		motor(motorA) = 20;
		motor(motorD) = 20;
		wait1Msec(1000);

			if(SensorValue(Color) == 2)
			{
				resetMotorEncoder(motorA);
				while(getMotorEncoder(motorA) <= 100)
				{
					motor(motorA) = 75;
					motor(motorD) = 25;
				}
				motor(motorA) = 0;
				motor(motorD) = 0;
				wait1Msec(10);
				resetMotorEncoder(motorA);
				while(getMotorEncoder(motorA) <= -100)
				{
					motor(motorA) = -75;
					motor(motorD) = -25;
				}


			}
					if(SensorValue(Color) == 4 || 6)
					{
						resetMotorEncoder(motorA);
						while(getMotorEncoder(motorA) <= 365)
						{
							motor(motorA) = 100;
							motor(motorD) = -100;
						}
						motor(motorA) = 25;
						motor(motorD) = 25;
						wait1Msec(7000);
					}
						motor(motorA) = -40;
						motor(motorD) = -40;
						wait1Msec(750);

						resetMotorEncoder(motorA);
						while(getMotorEncoder(motorA) <= 395)
						{
							motor(motorA) = 100;
							motor(motorD) = -100;
						}

						while(SensorValue(Sonar) >= 10)
							{
								motor(motorA) = 50;
								motor(motorD) = 50;

							}
								motor(motorA) = 20;
								motor(motorD) = 20;
								wait1Msec(1000);


								if(SensorValue(Color) == 4 || 6)
								{
									resetMotorEncoder(motorA);
									while(getMotorEncoder(motorA) <= 365)
									{
										motor(motorA) = 100;
										motor(motorD) = -100;
									}
											motor(motorA) = 25;
											motor(motorD) = 25;
											wait1Msec(7000);
								}
									motor(motorA) = -50;
									motor(motorD) = -50;
									wait1Msec(800);

									resetMotorEncoder(motorA);
									while(getMotorEncoder(motorA) <= 90)
										{
											motor(motorA) = -25;
											motor(motorD) = 25;
										}
											while(SensorValue(Sonar) >= 10)
											{
												motor(motorA) = 50;
												motor(motorD) = 50;

											}
												motor(motorA) = 20;
												motor(motorD) = 20;
												wait1Msec(1000);

											resetMotorEncoder(motorA);
											while(getMotorEncoder(motorA) <= 360)
											{
												motor(motorA) = -25;
												motor(motorD) = 25;
											}

}
